### ISSUE TITLE
Add the function of specify the number of cores to use 

### ISSUE THREAD

**Issue by martinpa13py** [hschimpf/parallel-sdk#18]
In some cases when you are running a high demanding process you would like to use a limit number of cores to do not incapacitate a production server. So in that cases it would be usefull a setter like coreLimit or something.

![Screenshot from 2023-09-24 15-57-59](https://github.com/hschimpf/parallel-sdk/assets/54122834/01fe539e-c678-47e6-8635-9f9247d7fb86)

**Comment by hschimpf** [comment]
Closed with #19
