### ISSUE TITLE
Function setMaxCpuPercentageUsage doesn't support float

### ISSUE THREAD

**Issue by martinpa13py** [hschimpf/parallel-sdk#21]
when I use the method setMaxCpuPercentageUsage with a float 

![image](https://github.com/hschimpf/parallel-sdk/assets/54122834/62ab3813-7e77-4ec5-8359-e025fa863a6f)

it calls the SetMaxCpuUsage class that only allows int
![image](https://github.com/hschimpf/parallel-sdk/assets/54122834/3310754e-cff2-40ec-9661-f85afb38439e)

then breaks with this exception

![image](https://github.com/hschimpf/parallel-sdk/assets/54122834/f6170130-f1ec-461d-bd77-c59f56370da3)

**Comment by hschimpf** [comment]
@martinpa13py Thanks for reporting this.
