### ISSUE TITLE
Segmentation fault (core dumped) when using progressbar on PHP 8.1+

### ISSUE THREAD

**Issue by hschimpf** [hschimpf/parallel-sdk#26]
The process fails when the progress bar is enabled on PHP versions 8.1 and following.

https://github.com/hschimpf/parallel-sdk/blob/5a9079be5aa82c497e4440e57872fe185d82335b/tests/ParallelTest.php#L75-L78

**Comment by hschimpf** [comment]
~We have array access everywhere, maybe related to https://github.com/krakjoe/parallel/issues/306 ?~

Maybe not 🫤

**Comment by realFlowControl** [comment]
Looks like you have a core dump, can you open an issue with a reproducer at https://github.com/krakjoe/parallel/issues/new ?
In the issue please also post the stacktrace.
I assume you are running on the latest released version? The current `develop` branch has a known issue.

**Comment by hschimpf** [comment]
> ... can you open an issue with a reproducer ... ?

Sure thing, opened [here](https://github.com/krakjoe/parallel/issues/316)

> In the issue please also post the stacktrace.

Done

> I assume you are running on the latest released version? ...

Yes, I'm using `ext-parallel` `v1.2.2`

**Comment by hschimpf** [comment]
`ext-parallel v1.2.5` solves the issue on PHP `v8.2`, `v8.3`, and `v8.4`.

PHP `v8.1` still fails when using the progress bar 😭.

Migrating to PHP `v8.2+` when is possible.
